name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, world!"

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Azure Container Registry
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/gh-actions:latest .
#           docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/gh-actions:latest